server:
  port: 2000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/netec-dev/poc-spring-cloud-bus-repo.git
          searchPaths: configuracion
    bus:      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest